---
title: "ESM232 A2 function application"
author: "Margaret Brickner, Nathalie Eegholm, Ruoyu Wang"
date: "4/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

source("R/almond_yield_anomaly.R")
```

```{r}
clim <- read.table("clim.txt")

precip <- clim %>% 
  filter(month == 1)

jan_precip_sum <- precip %>% 
  group_by(year) %>% 
  summarize(
    jan_precip_sum = sum(precip)
  )

temp <- clim %>% 
  filter(month == 2)

feb_temp_min <- temp %>% 
  group_by(year) %>%
  summarize(
    feb_tmin = min(tmin_c)
  )
  
#I added this code to calculate yield anomaly for each year. In my R script I called and filtered the data a bit differently, so can you make sure that this will get the right output in terms of calling the right columns, etc.? -Nathalie  

yset <- jan_precip_sum$year
  
yieldanoms<- NaN*(yset) #generate empty holding vector to store yield anomalies for each year

for(j in 1:length(yieldanoms)){ #loop through years

  yieldanoms[j]<-almond_yield_anomaly(feb_temp_min[j,2],
                         jan_precip_sum[j,2])
                         
                         }
                         
# simple plot of yield anomaly vs year, what other ways can we present the data?                         
plot(x=yset,y=yieldanoms, xlab="year", ylab="yield anomaly (tons/acre)",type = 'l', las = 1, lwd = 2, main = "Almond Yield Anomaly, Lobell et al., 2006")


#set of subplots to show precip and temp data along with yield anomaly. Not sure about how to best change margins/positions of plots
par(mfrow=c(2,1))#,mai = c(1, 1, 0.2, 1))#,oma = c(1, 1, 3, 1)) 

plot(x=yset,y=yieldanoms, xlab="Year", ylab="yield anomaly (tons/acre)",ylim=c(0,2000),type = 'l', las = 1, lwd = 2, cex.lab=0.6, cex.axis=0.75,main = "Almond Yield Anomaly,Lobell et al., 2006")

plot(x=yset,y=jan_precip_sum$jan_precip_sum, type ="l", ylab = "Precipitation (mm)",ylim=c(0,900),xlab = "Year",col = "blue", cex.lab=0.6, cex.axis=0.8)
par(new = TRUE)
plot(x=yset,y=feb_temp_min$feb_tmin, type = "l", xaxt = "n", yaxt = "n",ylab = "", xlab = "", col = "red", lty = 2, ylim=c(0,10), cex.lab=0.6)
axis(side = 4)
mtext("Temperature (C)", side = 4, line = 3, cex=0.6)
legend(x = 2000, y = 10, 
       lwd = 2,lty=c(1,2),
       legend = c('January Precipitation','Minimum February Temperature'),
       col = c("blue","red"), cex=0.3, bty = "n")

```

